server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: seckill
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 使用自定义异常
  mvc:
    throw-exception-if-no-handler-found: true
  # add-mappings: true表示如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配
  resources:
    add-mappings: false
  # 配置springboot对redis的依赖
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    # password:
    #设置jedis连接池
    jedis:
      pool:
        max-active: 50
        min-idle: 2

mq:
  nameserver:
    addr: 123.56.161.42:9876
  topicname: stock


