server:
  port: 8090
mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: seckill
    url: jdbc:mysql://127.0.0.1:3306/seckill
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver